### ISSUE TITLE
[MindSync] MindMapContainer 리팩토링 하기

### ISSUE THREAD

**Issue by yang1318** [yang1318/Troubleshooting-Record#1]
## Description
MindSync 프로젝트를 진행할 때 MindMapContainer라는 class를 이용해 MindMap 동작을 관리했는데, MindMapContainer 대신 더 좋은 구조가 없을지 고민이 필요하다고 생각돼 리팩토링 해볼 예정

## TODO
- [ ] MindMapContainer가 어떤 역할을 하고 있고, 왜 필요한 구조인지?
- [ ] MindMapContainer 대신 더 좋은 구조는 뭐가 있을지?
- [ ] 실제 코드 리팩토링 하기
